import { TrivyTableColumn } from '../../ui-elements/trivy-table/trivy-table.types';

export const clusterComplianceReportColumns: readonly TrivyTableColumn[] = [
  {
    field: 'name',
    header: 'Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px;white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'title',
    header: 'Title',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 265px; max-width: 265px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'totalFailCriticalCount',
    header: 'C',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['0'],
  },
  {
    field: 'totalFailHighCount',
    header: 'H',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px;',
    renderType: 'severityValue',
    extraFields: ['1'],
  },
  {
    field: 'totalFailMediumCount',
    header: 'M',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['2'],
  },
  {
    field: 'totalFailLowCount',
    header: 'L',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['3'],
  },
];

export const clusterComplianceReportDetailColumns: readonly TrivyTableColumn[] = [
  {
    field: 'severityId',
    header: 'Sev',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'severities',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'severityBadge',
  },
  {
    field: 'id',
    header: 'Id',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 90px; max-width: 90px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'name',
    header: 'Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 320px; max-width: 320px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'description',
    header: 'Description',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'checks',
    header: 'Checks',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'commands',
    header: 'Commands',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 150px; max-width: 150px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'totalFail',
    header: 'Failed',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal; text-align: right;',
    renderType: 'severityValue',
    extraFields: ['-1'],
  },
];

export const clusterComplianceReportDenormalizedColumns: readonly TrivyTableColumn[] = [
  {
    field: 'name',
    header: 'Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 120px; max-width: 120px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'description',
    header: 'Description',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 260px; max-width: 260px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'platform',
    header: 'Platf',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'title',
    header: 'Title',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 290px; max-width: 290px; white-space: normal;',
    renderType: 'link',
    extraFields: ['relatedResources'],
  },
  {
    field: 'type',
    header: 'Type',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 110px; max-width: 110px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'version',
    header: 'Ver',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 100px; max-width: 100px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'cron',
    header: 'Cron',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 110px; max-width: 110px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'reportType',
    header: 'RepType',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'totalPassCount',
    header: 'PassCount',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 150px; max-width: 150px; white-space: normal; text-align: right;',
    renderType: 'standard',
  },
  {
    field: 'totalFailCount',
    header: 'FailCount',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 150px; max-width: 150px; white-space: normal; text-align: right;',
    renderType: 'standard',
  },
  {
    field: 'updateTimestamp',
    header: 'Updated',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal;',
    renderType: 'date',
  },
  {
    field: 'detailId',
    header: 'Id',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 110px; max-width: 110px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'detailName',
    header: 'Detail Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 340px; max-width: 340px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'detailDescription',
    header: 'Detail Description',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 380px; max-width: 380px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'severityId',
    header: 'Sev',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'severities',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'severityBadge',
  },
  {
    field: 'checks',
    header: 'Checks',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'commands',
    header: 'Commands',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 150px; max-width: 150px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'totalFail',
    header: 'TotFail',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal; text-align: right;',
    renderType: 'severityValue',
    extraFields: ['-1'],
  },
];
