import { TrivyTableColumn } from '../../ui-elements/trivy-table/trivy-table.types';

export const exposedSecretReportColumns: readonly TrivyTableColumn[] = [
  {
    field: 'imageName',
    header: 'Image Name - Tag',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 265px; max-width: 265px; white-space: normal;',
    renderType: 'imageNameTag',
    extraFields: ['imageTag', 'imageEosl'],
  },
  {
    field: 'criticalCount',
    header: 'C',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['0'],
  },
  {
    field: 'highCount',
    header: 'H',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px;',
    renderType: 'severityValue',
    extraFields: ['1'],
  },
  {
    field: 'mediumCount',
    header: 'M',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['2'],
  },
  {
    field: 'lowCount',
    header: 'L',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['3'],
  },
];

export const exposedSecretReportDetailColumns: readonly TrivyTableColumn[] = [
  {
    field: 'severityId',
    header: 'Sev',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'severities',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'severityBadge',
  },
  {
    field: 'category',
    header: 'Category',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'ruleId',
    header: 'Id',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 95px; max-width: 95px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'match',
    header: 'Match',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px',
    renderType: 'standard',
  },
  {
    field: 'target',
    header: 'Target',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px',
    renderType: 'standard',
  },
  {
    field: 'title',
    header: 'Title',
    isFilterable: true,
    isSortable: false,
    multiSelectType: 'none',
    style: 'min-with: 200px; white-space: normal;',
    renderType: 'standard',
  },
];

export const exposedSecretReportDenormalizedColumns: readonly TrivyTableColumn[] = [
  {
    field: 'resourceName',
    header: 'Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 280px; max-width: 280px;',
    renderType: 'standard',
  },
  {
    field: 'resourceKind',
    header: 'Kind',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 110px; max-width: 110px;',
    renderType: 'standard',
  },
  {
    field: 'resourceContainerName',
    header: 'Container',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 170px; max-width: 170px;',
    renderType: 'standard',
  },
  {
    field: 'imageName',
    header: 'Image',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 210px; max-width: 210px;',
    renderType: 'standard',
  },
  {
    field: 'imageTag',
    header: 'Tag',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 115px; max-width: 115px;',
    renderType: 'standard',
  },
  {
    field: 'imageRepository',
    header: 'Repository',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 220px; max-width: 220px;',
    renderType: 'standard',
  },
  {
    field: 'severityId',
    header: 'Sev',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'severities',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'severityBadge',
  },
  {
    field: 'category',
    header: 'Category',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'ruleId',
    header: 'Id',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 95px; max-width: 95px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'match',
    header: 'Match',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px',
    renderType: 'standard',
  },
  {
    field: 'target',
    header: 'Target',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px',
    renderType: 'standard',
  },
  {
    field: 'title',
    header: 'Title',
    isFilterable: true,
    isSortable: false,
    multiSelectType: 'none',
    style: 'min-with: 200px; white-space: normal;',
    renderType: 'standard',
  },
];

