import { TrivyTableColumn } from '../../ui-elements/trivy-table/trivy-table.types';

export const rbacAssessmentReportColumns: readonly TrivyTableColumn[] = [
  {
    field: 'resourceName',
    header: 'Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 265px; max-width: 265px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'criticalCount',
    header: 'C',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['0'],
  },
  {
    field: 'highCount',
    header: 'H',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px;',
    renderType: 'severityValue',
    extraFields: ['1'],
  },
  {
    field: 'mediumCount',
    header: 'M',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['2'],
  },
  {
    field: 'lowCount',
    header: 'L',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['3'],
  },
];

export const rbacAssessmentReportDetailColumns: readonly TrivyTableColumn[] = [
  {
    field: 'severityId',
    header: 'Sev',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'severities',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'severityBadge',
  },
  {
    field: 'category',
    header: 'Category',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'checkId',
    header: 'Id',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 95px; max-width: 95px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'title',
    header: 'Title',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 180px; max-width: 180px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'description',
    header: 'Description',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 360px; max-width: 360px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'remediation',
    header: 'Remediation',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 360px; max-width: 360px; white-space: normal;',
    renderType: 'standard',
  },
];

export const rbacAssessmentReportDenormalizedColumns: readonly TrivyTableColumn[] = [
  {
    field: 'resourceName',
    header: 'Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 240px; max-width: 240px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'severityId',
    header: 'Sev',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'severities',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'severityBadge',
  },
  {
    field: 'category',
    header: 'Category',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 140px; max-width: 140px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'checkId',
    header: 'Id',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 95px; max-width: 95px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'title',
    header: 'Title',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 180px; max-width: 180px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'description',
    header: 'Description',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 360px; max-width: 360px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'remediation',
    header: 'Remediation',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 360px; max-width: 360px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'messages',
    header: 'Messages',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 500px; max-width: 500px; white-space: normal;',
    renderType: 'multiline',
  },
];

export const rbacAssessmentReportComparedTableColumns: readonly TrivyTableColumn[] = [
  {
    field: 'first',
    header: '1st',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'boolean',
  },
  {
    field: 'second',
    header: '2nd',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'boolean',
  },
  ... rbacAssessmentReportDetailColumns,
];
