import { TrivyTableColumn } from '../../ui-elements/trivy-table/trivy-table.types';

export const sbomReportDetailColumns: readonly TrivyTableColumn[] = [
  {
    field: 'name',
    header: 'Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'white-space: nowrap; text-overflow: ellipsis; overflow: hidden; width: 290px;',
    renderType: 'standard',
  },
  {
    field: 'version',
    header: 'Version',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px;',
    renderType: 'standard',
  },
  {
    field: 'criticalCount',
    header: 'C',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['0'],
  },
  {
    field: 'highCount',
    header: 'H',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px;',
    renderType: 'severityValue',
    extraFields: ['1'],
  },
  {
    field: 'mediumCount',
    header: 'M',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['2'],
  },
  {
    field: 'lowCount',
    header: 'L',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['3'],
  },
  {
    field: 'unknownCount',
    header: 'U',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['4'],
  },
  {
    field: 'level',
    header: 'Level',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px;',
    renderType: 'standard',
  },
];

export const sbomReportDenormalizedColumns: readonly TrivyTableColumn[] = [
  {
    field: 'imageName',
    header: 'Image Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 380px; max-width: 380px;',
    renderType: 'standard',
  },
  {
    field: 'imageTag',
    header: 'Image Tag',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 210px; max-width: 210px;',
    renderType: 'standard',
  },
  {
    field: 'imageDigest',
    header: 'Image Digest',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 550px; max-width: 550px;',
    renderType: 'standard',
  },
  {
    field: 'imageRepository',
    header: 'Repository',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 270px; max-width: 270px;',
    renderType: 'standard',
  },
  {
    field: 'hasVulnerabilities',
    header: 'Has VRs',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px;',
    renderType: 'boolean',
  },
  {
    field: 'criticalCount',
    header: 'C',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['0'],
  },
  {
    field: 'highCount',
    header: 'H',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px;',
    renderType: 'severityValue',
    extraFields: ['1'],
  },
  {
    field: 'mediumCount',
    header: 'M',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['2'],
  },
  {
    field: 'lowCount',
    header: 'L',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['3'],
  },
  {
    field: 'unknownCount',
    header: 'U',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 50px; max-width: 50px;',
    renderType: 'severityValue',
    extraFields: ['4'],
  },
];

export const sbomReportComparedTableColumns: readonly TrivyTableColumn[] = [
  {
    field: 'first',
    header: '1st',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'boolean',
  },
  {
    field: 'second',
    header: '2nd',
    isFilterable: false,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 90px; max-width: 90px;',
    renderType: 'boolean',
  },
  {
    field: 'name',
    header: 'Name',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'white-space: nowrap; text-overflow: ellipsis; overflow: hidden; width: 290px;',
    renderType: 'compareStacked',
  },
  {
    field: 'version',
    header: 'Version',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px;',
    renderType: 'compareStacked',
  },
  {
    field: 'purl',
    header: 'A purl',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 200px; max-width: 200px;',
    renderType: 'standard',
  },
];
