import { TrivyTableColumn } from '../../ui-elements/trivy-table/trivy-table.types';

export const watcherStateColumns: readonly TrivyTableColumn[] = [
  {
    field: 'kubernetesObjectType',
    header: 'k8s Object',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 200px; max-width: 200px;',
    renderType: 'unPascalCase',
    extraFields: ['Cr', ],
  },
  {
    field: 'namespaceName',
    header: 'NS',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 160px; max-width: 160px;',
    renderType: 'standard',
  },
  {
    field: 'status',
    header: 'Status',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 130px; max-width: 130px;',
    renderType: 'semaphore',
  },
  {
    field: 'mitigationMessage',
    header: 'Mitigation',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 330px; max-width: 330px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'lastException',
    header: 'Last Exception',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 330px; max-width: 330px; white-space: normal;',
    renderType: 'standard',
  },
  {
    field: 'lastEventMoment',
    header: 'Last Event',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 155px; max-width: 155px;',
    renderType: 'dateTime',
  },
  {
    field: 'eventsGauge',
    header: 'Items',
    isFilterable: true,
    isSortable: true,
    multiSelectType: 'none',
    style: 'width: 155px; max-width: 155px; text-align: right;',
    renderType: 'severityValue',
    extraFields: ['-1'],
  },
  {
    field: 'recreateAction',
    header: 'Manage',
    isFilterable: false,
    isSortable: false,
    multiSelectType: 'none',
    style: 'width: 185px; max-width: 185px; text-align: center;',
    renderType: 'action',
    extraFields: ['Recreate Watcher'],
  },
];
